@startuml
class Style {
    + fill : string <<get>> <<set>>
    + strokeWidth : string <<get>> <<set>>
    + strokeColor : string <<get>> <<set>>
    + Style()
    + getColor(letter:string) : string
}
@enduml
