@startuml
class LeftBrow {
    - X1 : int
    - Y1 : int
    - X2 : int
    - Y2 : int
    - Stroke : string
    - StrokeWidth : string
    - id : string
    + LeftBrow(style:Style)
    + <<override>> UpdateShape(direction:String, value:int) : void
    + <<override>> UpdateStyle(color:string) : void
    + <<override>> getId() : string
    + <<override>> ToSvg() : string
}
AbstractShape <|-- LeftBrow
LeftBrow o-> "r" Random
@enduml
