@startuml
class Ellipse {
    r : Random
    - CX : int
    - CY : int
    - RX : int
    - RY : int
    - Fill : string
    - Stroke : string
    - StrokeWidth : string
    + Ellipse()
    + <<override>> ToSvg() : string
}
AbstractShape <|-- Ellipse
@enduml
