@startuml
class Polygon {
    r : Random
    - Fill : string
    - Stroke : string
    - StrokeWidth : string
    - Points : string
    + Polygon()
    + <<override>> ToSvg() : string
}
AbstractShape <|-- Polygon
@enduml
