@startuml
class Rectangle {
    r : Random
    - X : int
    - Y : int
    - Height : int
    - Width : int
    - Fill : string
    - Stroke : string
    - StrokeWidth : string
    + Rectangle()
    + <<override>> ToSvg() : string
}
AbstractShape <|-- Rectangle
@enduml
