@startuml
class Line {
    - X1 : int
    - Y1 : int
    - X2 : int
    - Y2 : int
    - Stroke : string
    - StrokeWidth : string
    + Line(style:Style)
    + <<override>> ToSvg() : string
}
AbstractShape <|-- Line
Line o-> "r" Random
@enduml
