@startuml
class Canvas {
    - Width : int
    - Height : int
    + Canvas(width:int, height:int)
    + Canvas(shapes:List<AbstractShape>, width:int, height:int)
    + AddShape(shape:AbstractShape) : void
    + AddShape(i:int, shape:AbstractShape) : void
    + {static} deleteShape(i:int) : void
    + ToSvg() : string
    + {static} <<async>> SaveFile(text:string) : Task
}
class "List`1"<T> {
}
Canvas --> "Shapes<AbstractShape>" "List`1"
Canvas o-> "BoilerSVG" String
@enduml
