@startuml
class Circle {
    r : Random
    - CX : int
    - CY : int
    - Radius : int
    - Fill : string
    - Stroke : string
    - StrokeWidth : string
    + Circle()
    + <<override>> ToSvg() : string
}
AbstractShape <|-- Circle
@enduml
