@startuml
class Caretaker {
    + Caretaker(originator:Originator)
    + Backup() : void
    + Undo() : void
    + Redo() : void
}
class "List`1"<T> {
}
Caretaker o-> "_mementos<Memento>" "List`1"
Caretaker o-> "_removedMementos<Memento>" "List`1"
Caretaker o-> "_originator" Originator
@enduml
