@startuml
class Canvas {
    - Width : int
    - Height : int
    + Canvas(width:int, height:int)
    + Canvas(shapes:List<AbstractShape>, width:int, height:int)
    + AddShape(shape:AbstractShape) : void
    + clearCanvas() : void
    + setCanvas(l:List<AbstractShape>) : void
    + getShapes() : List<AbstractShape>
    + ToSvg() : string
    + {static} <<async>> SaveFile(text:string) : Task
}
class "List`1"<T> {
}
Canvas --> "Shapes<AbstractShape>" "List`1"
Canvas o-> "BoilerSVG" String
@enduml
